config/routes.rb
Rails.application.routes.draw do

    resources :users, only: [:new, :create]

    resources :sessions, only: [:new, :create] do
      delete :destroy, on: :collection
    end

    resources :suggestions do
        resources :members, only: [:create, :update, :destroy]

    get :search, on: :collection
    post :flag, on: :member
    post :mark_done

    resources :ideas, only: [:create, :destroy]
      resources :likes, only: [:create, :destroy]
  end

resources :likes, only: [:index]

   root 'home#index'
end

app/models/idea.rb
class Idea < ActiveRecord::Base
  belongs_to :suggestion
  validates :body, presence: true, uniqueness: {scope: :suggestion_id}
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :suggestion

  validates :user_id, uniqueness: {scope: :suggestion_id}
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :user
  belongs_to :suggestion

  validates :user, uniqueness: {scope: :suggestion}
end

app/models/suggestion.rb
class Suggestion < ActiveRecord::Base
  has_many :ideas, dependent: :destroy
  belongs_to :user

  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user

  has_many :members, dependent: :destroy
  has_many :members_users, through: :members, source: :user

  validates(:title, {presence: {message: "must be present!"}, uniqueness: true})

  validates :body, presence:   true,           length:     {minimum: 7},                 uniqueness: {scope: :title}

  validates :view_count, numericality: {greater_than_or_equal_to: 0}

  def self.recent(count)
    where("created_at > ?", 2.day.ago).limit(count)
  end

  def self.search(word)
    where("title ILIKE :word OR body ILIKE :word", {word: "%#{word}%"})
  end
  def new_first_ideas
    ideas.order(created_at: :desc)
  end

  def liked_by?(user)
    likes.exists?(user: user)
  end

  def like_for(user)
    likes.find_by_user_id user
  end

  def member_of?(user)
    members.exists?(user: user)
  end

  private

  def cap_title
    self.title = title.capitalize if title
  end

  def squeeze_title_and_body
    self.title.squeeze!(" ") if title
    self.body.squeeze!(" ") if body
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :suggstions, dependent: :nullify

  has_many :likes, dependent: :destroy
  has_many :liked_suggestions, through: :likes, source: :suggestion

  has_many :memberships, dependent: :destroy
  has_many :membershipped_suggestions, through: :memberships, source: :suggestion

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true,
                    uniqueness: true,
                    format: /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  def full_name
    "#{first_name} #{last_name}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def user_signed_in?
  session[:user_id].present?
  end
  helper_method :user_signed_in?

  def sign_in(user)
    session[:user_id] = user.id
  end

  def authenticate_user!
    redirect_to new_session_path, alert: "who dis?" unless user_signed_in?
  end

  def current_suggestion
    @current_suggestion ||= Suggestion.find params[:suggestion_id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  def create
    @idea          = Idea.new answer_params
    @suggestion        = Suggestion.find params[:suggestion_id]
    @idea.suggestion = @idea
    if @idea.save
      redirect_to suggestion_path(@suggestion), notice: "Idea created!"
    else
      render "/suggestions/show"
    end
  end

  def destroy
  suggestion = Suggestion.find params[:suggestion_id]
    idea   = Idea.find params[:id]
    idea.destroy
    redirect_to suggestion_path(suggestion), notice: "Idea deleted"
  end

  private

  def answer_params
    params.require(:idea).permit(:body)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  before_action :authenticate_user!

  def index
    @suggstions = current_user.liked_suggestions
  end

  def create
    suggestion = Suggestion.find params[:suggestion_id]
    l        = Like.new(suggetsion: suggetsion, user: current_user) unless can? :manage, @suggestion, notice: "Calm down, bro. We know you like your own suggestions."
    if l.save
      redirect_to suggestion_path(suggestion), notice: "We like that you like this!"
    else
      redirect_to suggestion_path(suggestion), alert: "Liked already."
    end
  end

  def destroy
    like     = Like.find params[:id]
    suggestion = Suggestion.find params[:suggestion_id]
    like.destroy if can? :destroy, Like
    redirect_to suggestion_path(suggestion), notice: "Un-liked"
  end

end

app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController

  before_action :find_suggestion, only: [:show, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]
  before_action :authorize_owner, only: [:edit, :destroy,:update]

def new
  @suggestion = Sugggestion.new
end

def create
  @suggestion = Sugggestion.new suggestion_params
  @suggestion.user = current_user
    if @suggestion.save
      redirect_to suggestion_path(@suggestion), notice: "Thanks for the suggestion!"
    else
      flash[:alert] = "Come again now?"
      render :new
    end
  end

def show
  @suggestion.increment!(:view_count)
  @idea = Idea.new
end

def index
  @suggestions = Suggestion.order(created_at: :desc)
end

def update
  if @suggestion.update suggestion_params
    redirect_to suggestion_path(@suggestion), notice: "your suggestion has been updated"
  else
    render :edit
  end
end

def destroy
  @suggestion.destroy
  redirect_to suggestion_path, notice: "Suggestion rescinded"
end

private

def suggestion_params
  params.require(:suggestion).permit(:title, :body)
end

def find_suggestion
  @suggestion = Suggestion.find params[:id]
end

def authorize_owner
  redirect_to root_path, alert: "You shall not pass!" unless can? :manage, @suggestion
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit(:first_name, :last_name, :email,:password, :password_confirmation)
@user = User.new user_params
if @user.save
  sign_in(@user)
  redirect_to root_path, notice: "One of us! One of us!"
else
  render :new
end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/suggestions_helper.rb
module SuggestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Suggestions and Ideas</h1>
<p>Make a suggestion, and let the community share ideas with you.</p>
  <%= link_to "New Suggestion", new_suggestion_path %>

app/views/ideas/new.html.erb
<%= form_for :thought do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quizzical</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/likes/index.html.erb
<h1>Suggestions you liked:</h1>

<% @suggstions.each do |suggestion| %>
  <%= link_to suggestion.title, suggestion %>
  <hr>
<% end %>

app/views/suggestions/_form.html.erb
<%= @suggestion.errors.full_messages.join(", ") %>
<%= form_for @suggestion do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <%= f.submit %>
<% end %>

app/views/suggestions/index.html.erb
<h1>Suggestions</h1>

<% @suggstions.each do |suggestion| %>
  <%= link_to suggestion.title, suggestion_path(suggestion) %>
  <hr>
<% end %>
<%= paginate @suggstions %>

app/views/suggestions/show.html.erb
<div>
  Title:
  <%= @suggestion.title.titleize %>

  Text:
  <%= @suggestion.body %>
</div>
<p>Created By: <%= @question.user.first_name if @question.user %></p>
<% if @question.liked_by?(current_user) %>
  <%= link_to "you like this",
              suggestion_like_path(@suggestion, @suggestion.like_for(current_user)),
              method: :delete %>
<% else %>
  <%= link_to "you could like this",
              suggestion_likes_path(@suggestion),
              method: :post %>
<% end %>
(<%= @suggestion.likes.count %>)

<% if can? :manage, @suggestion %>
  <%= link_to "Delete", question_path(@question),                        method: :delete, data:   {confirm: "Are you sure?"} %>
<% end %>

<% if @suggestion.membership_added_by?(current_user) %>
  <%= link_to "Leave Group",
              question_membership_path(@suggestion, current_user_membership),
              method: :delete,
              data: {disable_with: "...."} %>
 (<%= @suggestion.membership_sum %>)
<% else  %>
 <%= link_to "Join Group",
             suggestion_memberships_path(@question, {membership: {is_up: true}}),
             method: :post %>
 (<%= @suggestion.membership_sum %>)

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>